"""Added session id for user

Revision ID: c422d323382c
Revises: d62fc23798b3
Create Date: 2025-04-11 15:39:16.072500

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c422d323382c'
down_revision = 'd62fc23798b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventoryevents', sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(),
                                               nullable=True, default=None))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventoryevents', 'session_id')
    # ### end Alembic commands ###
