"""Create Event tables

Revision ID: bd4fe18d77f0
Revises: 
Create Date: 2025-02-27 12:41:13.903404

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = 'bd4fe18d77f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventoryevents',
    sa.Column('event_id', UUID(as_uuid=True), nullable=False),
    sa.Column('event_type', sa.Enum('UPDATED', 'DELETED', 'CREATED', 'ARCHIVED', name='eventtype'), nullable=False),
    sa.Column('instance', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attribute', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_inventoryevents_event_id'), 'inventoryevents', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventoryevents_event_id'), table_name='inventoryevents')
    op.drop_table('inventoryevents')
    # ### end Alembic commands ###
